// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase/user_output_port.go
//
// Generated by this command:
//
//	mockgen -source=./usecase/user_output_port.go -destination=./mock/usecase/user_output_port.go -package usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	reflect "reflect"

	entity "github.com/lee212400/myProject/domain/entity"
	dto "github.com/lee212400/myProject/usecase/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockUserOutputPort is a mock of UserOutputPort interface.
type MockUserOutputPort struct {
	ctrl     *gomock.Controller
	recorder *MockUserOutputPortMockRecorder
	isgomock struct{}
}

// MockUserOutputPortMockRecorder is the mock recorder for MockUserOutputPort.
type MockUserOutputPortMockRecorder struct {
	mock *MockUserOutputPort
}

// NewMockUserOutputPort creates a new mock instance.
func NewMockUserOutputPort(ctrl *gomock.Controller) *MockUserOutputPort {
	mock := &MockUserOutputPort{ctrl: ctrl}
	mock.recorder = &MockUserOutputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserOutputPort) EXPECT() *MockUserOutputPortMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserOutputPort) CreateUser(ctx *entity.Context, out *dto.CreateUserOutputDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, out)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserOutputPortMockRecorder) CreateUser(ctx, out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserOutputPort)(nil).CreateUser), ctx, out)
}

// DeleteUser mocks base method.
func (m *MockUserOutputPort) DeleteUser(ctx *entity.Context, out *dto.DeleteUserOutputDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, out)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserOutputPortMockRecorder) DeleteUser(ctx, out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserOutputPort)(nil).DeleteUser), ctx, out)
}

// GetUser mocks base method.
func (m *MockUserOutputPort) GetUser(ctx *entity.Context, out *dto.GetUserOutputDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, out)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserOutputPortMockRecorder) GetUser(ctx, out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserOutputPort)(nil).GetUser), ctx, out)
}

// UpdateUser mocks base method.
func (m *MockUserOutputPort) UpdateUser(ctx *entity.Context, out *dto.UpdateUserOutputDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, out)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserOutputPortMockRecorder) UpdateUser(ctx, out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserOutputPort)(nil).UpdateUser), ctx, out)
}
