// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/lee212400/myProject/infrastructure/repository"
	"github.com/lee212400/myProject/interface/handler"
	"github.com/lee212400/myProject/usecase"
)

// Injectors from wire.go:

func InitOrder() *handler.OrderHandler {
	orderRepositoryImpl := repository.NewOrderRepositoryImpl()
	orderInteractor := usecase.NewOrderInteractor(orderRepositoryImpl)
	orderHandler := handler.NewOrderHandler(orderInteractor)
	return orderHandler
}
