// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SampleServiceClient is the client API for SampleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SampleServiceClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	GetData(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (SampleService_GetDataClient, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	ChatStream(ctx context.Context, opts ...grpc.CallOption) (SampleService_ChatStreamClient, error)
	ChatToWay(ctx context.Context, opts ...grpc.CallOption) (SampleService_ChatToWayClient, error)
}

type sampleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSampleServiceClient(cc grpc.ClientConnInterface) SampleServiceClient {
	return &sampleServiceClient{cc}
}

func (c *sampleServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/sample.SampleService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sampleServiceClient) GetData(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (SampleService_GetDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &SampleService_ServiceDesc.Streams[0], "/sample.SampleService/GetData", opts...)
	if err != nil {
		return nil, err
	}
	x := &sampleServiceGetDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SampleService_GetDataClient interface {
	Recv() (*StreamResponse, error)
	grpc.ClientStream
}

type sampleServiceGetDataClient struct {
	grpc.ClientStream
}

func (x *sampleServiceGetDataClient) Recv() (*StreamResponse, error) {
	m := new(StreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sampleServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/sample.SampleService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sampleServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/sample.SampleService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sampleServiceClient) ChatStream(ctx context.Context, opts ...grpc.CallOption) (SampleService_ChatStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &SampleService_ServiceDesc.Streams[1], "/sample.SampleService/ChatStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &sampleServiceChatStreamClient{stream}
	return x, nil
}

type SampleService_ChatStreamClient interface {
	Send(*ChatRequest) error
	CloseAndRecv() (*ChatResponse, error)
	grpc.ClientStream
}

type sampleServiceChatStreamClient struct {
	grpc.ClientStream
}

func (x *sampleServiceChatStreamClient) Send(m *ChatRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sampleServiceChatStreamClient) CloseAndRecv() (*ChatResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ChatResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sampleServiceClient) ChatToWay(ctx context.Context, opts ...grpc.CallOption) (SampleService_ChatToWayClient, error) {
	stream, err := c.cc.NewStream(ctx, &SampleService_ServiceDesc.Streams[2], "/sample.SampleService/ChatToWay", opts...)
	if err != nil {
		return nil, err
	}
	x := &sampleServiceChatToWayClient{stream}
	return x, nil
}

type SampleService_ChatToWayClient interface {
	Send(*Chat) error
	Recv() (*Chat, error)
	grpc.ClientStream
}

type sampleServiceChatToWayClient struct {
	grpc.ClientStream
}

func (x *sampleServiceChatToWayClient) Send(m *Chat) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sampleServiceChatToWayClient) Recv() (*Chat, error) {
	m := new(Chat)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SampleServiceServer is the server API for SampleService service.
// All implementations must embed UnimplementedSampleServiceServer
// for forward compatibility
type SampleServiceServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	GetData(*StreamRequest, SampleService_GetDataServer) error
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	ChatStream(SampleService_ChatStreamServer) error
	ChatToWay(SampleService_ChatToWayServer) error
	mustEmbedUnimplementedSampleServiceServer()
}

// UnimplementedSampleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSampleServiceServer struct {
}

func (UnimplementedSampleServiceServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedSampleServiceServer) GetData(*StreamRequest, SampleService_GetDataServer) error {
	return status.Errorf(codes.Unimplemented, "method GetData not implemented")
}
func (UnimplementedSampleServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedSampleServiceServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedSampleServiceServer) ChatStream(SampleService_ChatStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedSampleServiceServer) ChatToWay(SampleService_ChatToWayServer) error {
	return status.Errorf(codes.Unimplemented, "method ChatToWay not implemented")
}
func (UnimplementedSampleServiceServer) mustEmbedUnimplementedSampleServiceServer() {}

// UnsafeSampleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SampleServiceServer will
// result in compilation errors.
type UnsafeSampleServiceServer interface {
	mustEmbedUnimplementedSampleServiceServer()
}

func RegisterSampleServiceServer(s grpc.ServiceRegistrar, srv SampleServiceServer) {
	s.RegisterService(&SampleService_ServiceDesc, srv)
}

func _SampleService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SampleServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample.SampleService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SampleServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SampleService_GetData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SampleServiceServer).GetData(m, &sampleServiceGetDataServer{stream})
}

type SampleService_GetDataServer interface {
	Send(*StreamResponse) error
	grpc.ServerStream
}

type sampleServiceGetDataServer struct {
	grpc.ServerStream
}

func (x *sampleServiceGetDataServer) Send(m *StreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SampleService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SampleServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample.SampleService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SampleServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SampleService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SampleServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample.SampleService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SampleServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SampleService_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SampleServiceServer).ChatStream(&sampleServiceChatStreamServer{stream})
}

type SampleService_ChatStreamServer interface {
	SendAndClose(*ChatResponse) error
	Recv() (*ChatRequest, error)
	grpc.ServerStream
}

type sampleServiceChatStreamServer struct {
	grpc.ServerStream
}

func (x *sampleServiceChatStreamServer) SendAndClose(m *ChatResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sampleServiceChatStreamServer) Recv() (*ChatRequest, error) {
	m := new(ChatRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SampleService_ChatToWay_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SampleServiceServer).ChatToWay(&sampleServiceChatToWayServer{stream})
}

type SampleService_ChatToWayServer interface {
	Send(*Chat) error
	Recv() (*Chat, error)
	grpc.ServerStream
}

type sampleServiceChatToWayServer struct {
	grpc.ServerStream
}

func (x *sampleServiceChatToWayServer) Send(m *Chat) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sampleServiceChatToWayServer) Recv() (*Chat, error) {
	m := new(Chat)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SampleService_ServiceDesc is the grpc.ServiceDesc for SampleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SampleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sample.SampleService",
	HandlerType: (*SampleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _SampleService_SayHello_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _SampleService_Search_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _SampleService_GetUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetData",
			Handler:       _SampleService_GetData_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ChatStream",
			Handler:       _SampleService_ChatStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ChatToWay",
			Handler:       _SampleService_ChatToWay_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "sample.proto",
}
