// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sample

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Sample struct {
	ID          int64
	SampleTitle string
	SampleMemo  pgtype.Text
}
