apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.imageName }} # <- Minikube内部でbulidしたイメージ
          imagePullPolicy: Never
          ports:
            - containerPort: 50051  # gRPC
            - containerPort: 8080   # HTTP or grpc-gateway
          command: ["/bin/sh", "-c", "./run.sh"]  
          resources:
              requests:
                memory: "100Mi"
              limits:
                memory: "200Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 30
          envFrom:
            - configMapRef:
                name: myapp-config
            - secretRef:
                name: myapp-secret
          env:
            - name: MY_DOMAIN
              value: {{ .Values.myDomain }}