FROM golang:1.24-alpine AS builder

WORKDIR /work

COPY go.mod go.sum ./
RUN go mod download

COPY proto/ proto/
COPY cmd/ cmd/

COPY ./rpc /work/rpc

RUN go build -ldflags="-s -w" -o app ./cmd/main.go

FROM alpine:latest

WORKDIR /work
# ビルド結果コピー
COPY --from=builder /work/app .