name: WorkFlow_Dispatch

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      environment:
        description: 'Select environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod
      params:
        description: 'Parameters'
        required: false

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x src/grpc-api/workflow/jobs/test.sh

      - name: Run script with environment variables
        run: src/grpc-api/workflow/jobs/test.sh

      - run: |
          echo "Log level: $LEVEL"
          echo "environment: $ENVIRONMENT"
          echo "params: $PARAMS"
        env:
          LEVEL: ${{ inputs.logLevel }}
          ENVIRONMENT: ${{ inputs.environment }}
          PARAMS: ${{ inputs.params }}